spring.application.name=gestor-estoque

# Configuração do Banco de Dados (H2 Local / PostgreSQL na Nuvem)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/estoquedb;AUTO_SERVER=TRUE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}

# Console H2 (Apenas Local)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração de Segurança JWT
jwt.secret=${JWT_SECRET:ChaveSuperSecretaECompridaParaOJWTDoGestorDeEstoqueComMuitoMaisDe32Caracteres123456}
jwt.expiration=86400000
